name: dotnet integration tests
on: [push]
env:
  DB_HOST: 172.20.0.3
  DB_PORT: 1433
  DB_NAME: master
  DB_USER: sa
  DB_PASSWORD: PandaNinja13.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Create .env
        run: |
          touch .env
          echo "DB_HOST=$DB_HOST" >> .env
          echo "DB_PORT=$DB_PORT" >> .env
          echo "DB_NAME=$DB_NAME" >> .env
          echo "DB_USER=$DB_USER" >> .env
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
      - name: Up database container
        run: docker compose up -d database
      - name: Show container IP
        run: |
          docker inspect -f '{{ range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ordering-api-database
      - name: Setup Dotnet Entity Framework
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
      - name: Apply migrations
        run: dotnet ef database update
      - name: Run integration tests
        run: make integration-test
