name: dotnet integration tests
on: [push]
env:
  DB_HOST: localhost
  DB_PORT: 1433
  DB_NAME: master
  DB_USER: sa
  DB_PASSWORD: PandaNinja13.
  TESTING: true
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Create .env.test
        run: |
          touch .env.test
          echo "TESTING=$TESTING" >> .env.test
          echo "DB_HOST=$DB_HOST" >> .env.test
          echo "DB_PORT=$DB_PORT" >> .env.test
          echo "DB_NAME=$DB_NAME" >> .env.test
          echo "DB_USER=$DB_USER" >> .env.test
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env.test
      - name: Up database container
        run: docker compose --env-file .env.test up -d test-database
      - name: Docker container info
        run: docker inspect ordering-api-database
      - name: Append DB_HOST to .env.test
        run: |
          echo "DB_HOST=$(docker inspect -f '{{ range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ordering-api-database)" >> .env.test
      - name: Setup Dotnet Entity Framework
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
      - name: Apply migrations
        run: |
          make migrations.testing.run
      - name: Run integration tests
        run: make test.integration.run
